// 批量翻译 exercises.json 中 nameZh===name（未翻译）的动作名，写回 nameZh。
// 策略：术语词典（含多词短语）+ 最长匹配贪心组合。
const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, 'data', 'exercises.json');
const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));

// ---- 词典：key 小写，按长度降序匹配（多词短语优先）----
const DICT = {
  // 短语/复合动作（多词，优先）
  'full body': '全身',
  'upper body': '上身',
  'lower body': '下身',
  'bench press': '卧推',
  'shoulder press': '肩上推举',
  'military press': '肩上推举',
  'overhead press': '过顶推举',
  'chest press': '胸推',
  'leg press': '腿举',
  'romanian deadlift': '罗马尼亚硬拉',
  'stiff leg deadlift': '直腿硬拉',
  'straight leg deadlift': '直腿硬拉',
  'deadlift': '硬拉',
  'split squat': '分腿蹲',
  'curtsey squat': '侧弓步蹲',
  'pistol squat': '手枪蹲',
  'jump squat': '跳深蹲',
  'speed squat': '快速深蹲',
  'pulse squat': '脉冲深蹲',
  'squat': '深蹲',
  'forward lunge': '前箭步蹲',
  'reverse lunge': '后箭步蹲',
  'lateral lunge': '侧箭步蹲',
  'walking lunge': '行走箭步蹲',
  'lunge': '箭步蹲',
  'step up': '登阶',
  'step-up': '登阶',
  'pull up': '引体向上',
  'pullup': '引体向上',
  'chin up': '反握引体',
  'push up': '俯卧撑',
  'pushup': '俯卧撑',
  'inverted row': '仰卧划船',
  'preacher curl': '牧师凳弯举',
  'hammer curl': '锤式弯举',
  'concentration curl': '集中弯举',
  'bicep curl': '二头弯举',
  'triceps extension': '三头屈伸',
  'triceps pushdown': '三头下压',
  'leg curl': '腿弯举',
  'leg extension': '腿屈伸',
  'sit up': '仰卧起坐',
  'situp': '仰卧起坐',
  'sit ups': '仰卧起坐',
  'side bend': '体侧屈',
  'side plank': '侧平板',
  'toe touch': '触趾',
  'calf raise': '提踵',
  'hip raise': '髋部上抬',
  'hip thrust': '臀推',
  'glute bridge': '臀桥',
  'chest fly': '胸飞鸟',
  'cross body': '交叉',
  'close grip': '窄握',
  'wide grip': '宽握',
  'neutral grip': '对握',
  'reverse grip': '反握',
  'overhand grip': '正握',
  'underhand grip': '反握',
  'single arm': '单臂',
  'one arm': '单臂',
  'single leg': '单腿',
  'one leg': '单腿',
  'two arm': '双臂',
  'both arms': '双臂',
  'two leg': '双腿',
  'both legs': '双腿',
  'smith machine': '史密斯机',
  'resistance band': '弹力带',
  'medicine ball': '药球',
  'stability ball': '瑞士球',
  'swiss ball': '瑞士球',
  'exercise ball': '健身球',
  'bodyweight': '自重',
  'body weight': '自重',
  'ez bar': 'EZ杆',
  'v bar': 'V杆',
  'v handle': 'V柄',
  'v grip': 'V握',
  'lower back': '下背',
  'upper back': '上背',
  'lower arms': '前臂',
  'upper arms': '上臂',
  'inner thigh': '大腿内侧',
  'outer thigh': '大腿外侧',
  'half kneeling': '半跪',
  'bent over': '俯身',
  'on ball': '球上',
  'on bench': '凳上',
  'warm up': '热身',
  'cool down': '放松',
  'drop set': '递减组',
  'super set': '超级组',
  'lat pulldown': '高位下拉',
  'good morning': '早安式',
  'behind head': '颈后',
  'behind back': '背后',
  'rack pull': '架上拉',
  'french press': '法式推举',
  'jumping jack': '开合跳',
  'drop jump': '跳深',
  'box jump': '箱跳',
  'star jump': '星形跳',
  'skater': '滑冰跳',
  'burpee': '波比跳',
  'mountain climber': '登山者',
  'bicycle crunch': '自行车卷腹',
  'dead bug': '死虫',
  'jackknife': '折刀',
  'superman': '超人式',
  'spider curl': '蜘蛛弯举',
  'zottman curl': '佐特曼弯举',
  'scott curl': '斯科特弯举',
  'skull crusher': '仰卧臂屈伸',
  'skullcrusher': '仰卧臂屈伸',
  'hack squat': '哈克深蹲',
  'sumo deadlift': '相扑硬拉',
  'pendlay row': '彭德雷划船',
  'renegade row': '叛逆划船',
  'turkish get up': '土耳其起立',
  'farmers walk': '农夫行走',
  'monster walk': '怪兽走',
  'waiter walk': '侍者走',
  'captains chair': '悬垂举腿椅',
  'windshield wipers': '雨刷',
  'around the world': '环绕',
  'around the clock': '环绕',
  'clean and jerk': '抓举挺举',
  'power clean': '力量翻',
  'snatch': '抓举',
  'sissy squat': '少女深蹲',
  'prisoner squat': '囚徒深蹲',
  'pallof press': '帕洛夫推举',
  'jm press': 'JM推举',
  'svend press': '斯文德推举',
  'face pull': '面拉',
  'landmine': '地雷杆',
  'ab roller': '腹肌轮',
  'ab wheel': '腹肌轮',
  'slam ball': '砸药球',
  'stationary bike': '固定单车',
  'air bike': '风阻单车',
  'hindu pushup': '印度俯卧撑',
  'kipping pull up': '摆动引体',
  'downward dog': '下犬式',
  'human flag': '人体旗帜',
  'skin the cat': '皮猫式',
  'butterfly': '反向飞鸟',
  'internal rotation': '内旋',
  'external rotation': '外旋',
  'pelvic tilt': '骨盆倾斜',
  'anti rotation': '抗旋转',
  'bosu': 'BOSU球',
  'cable elevator': '绳索升降',
  'muscle up': '双力臂',
  'muscle ups': '双力臂',
  'chin ups': '反握引体',
  'pull ups': '引体向上',
  'push ups': '俯卧撑',
  'bottoms up': '底朝上',
  'body up': '身体上抬',
  'butt ups': '臀上举',
  'otis up': '奥蒂斯起',
  'wheel rollerout': '腹肌轮',
  'l sit': 'L支撑',
  'l-sit': 'L支撑',

  // 器械
  'dumbbell': '哑铃',
  'barbell': '杠铃',
  'kettlebell': '壶铃',
  'cable': '绳索',
  'smith': '史密斯机',
  'lever': '杠杆',
  'machine': '器械',
  'band': '弹力带',
  'ball': '球',
  'bench': '凳',
  'plate': '杠铃片',
  'ez': 'EZ',
  'weighted': '负重',
  'rope': '绳',
  'bar': '杆',
  'handle': '柄',
  'grip': '握',
  'resistance': '抗阻',

  // 部位
  'chest': '胸',
  'pec': '胸',
  'back': '背',
  'shoulder': '肩',
  'biceps': '二头',
  'bicep': '二头',
  'triceps': '三头',
  'tricep': '三头',
  'abs': '腹',
  'abdominal': '腹',
  'abdominals': '腹',
  'core': '核心',
  'glutes': '臀',
  'glute': '臀',
  'leg': '腿',
  'legs': '腿',
  'calf': '小腿',
  'calves': '小腿',
  'hamstring': '腘绳肌',
  'quad': '股四头',
  'quadriceps': '股四头',
  'forearm': '前臂',
  'wrist': '腕',
  'hip': '髋',
  'neck': '颈',
  'oblique': '腹斜肌',
  'lats': '背阔肌',
  'lat': '背阔肌',
  'traps': '斜方肌',
  'trapezius': '斜方肌',
  'deltoid': '三角肌',
  'delts': '三角肌',

  // 动作/动词
  'press': '推举',
  'push': '推',
  'pull': '拉',
  'row': '划船',
  'shrug': '耸肩',
  'curl': '弯举',
  'crunch': '卷腹',
  'twist': '转体',
  'twisting': '转体',
  'plank': '平板支撑',
  'fly': '飞鸟',
  'flye': '飞鸟',
  'pullover': '上拉',
  'extension': '伸展',
  'flexion': '屈曲',
  'stretch': '拉伸',
  'rotation': '旋转',
  'rotate': '旋转',
  'raise': '上举',
  'bridge': '桥',
  'kick': '踢',
  'kicks': '踢腿',
  'march': '踏步',
  'walk': '行走',
  'jog': '慢跑',
  'run': '跑',
  'jump': '跳',
  'climb': '爬',
  'crawl': '爬行',
  'roll': '滚动',
  'circle': '画圈',
  'circular': '画圈',
  'lift': '上抬',
  'lower': '下放',
  'drag': '拖',
  'carry': '负重行走',
  'squeeze': '挤压',
  'gripless': '无握',
  'cross': '交叉',
  'contra': '对侧',
  'contralateral': '对侧',
  'ipsilateral': '同侧',
  'reach': '伸展够取',
  'touch': '触',
  'hold': '保持',
  'swimmer': '游泳',
  'quick feet': '快速脚',
  'inchworm': '尺蠖',
  'astride': '跨',
  'cossack': '哥萨克',
  'frankenstein': '弗兰肯斯坦',
  'cuban': '古巴',
  'dip': '臂屈伸',
  'knee': '膝',
  'elbow': '肘',
  'finger': '手指',
  'thumb': '拇指',
  'hands': '手',
  'hand': '手',
  'foot': '脚',
  'feet': '脚',
  'toe': '脚尖',
  'heel': '脚跟',

  // 姿态/方向/修饰
  'seated': '坐姿',
  'standing': '站姿',
  'lying': '躺姿',
  'incline': '上斜',
  'decline': '下斜',
  'upright': '直立',
  'prone': '俯身',
  'supine': '仰卧',
  'flat': '平板',
  'hanging': '悬垂',
  'kneeling': '跪姿',
  'bent': '俯身',
  'supported': '支撑',
  'side': '侧',
  'front': '前',
  'rear': '后',
  'inner': '内',
  'outer': '外',
  'upper': '上',
  'high': '高',
  'low': '低',
  'deep': '深',
  'wide': '宽',
  'narrow': '窄',
  'close': '窄',
  'partial': '半程',
  'full': '全程',
  'slow': '慢速',
  'fast': '快速',
  'single': '单',
  'double': '双',
  'both': '双',
  'reverse': '反向',
  'forward': '前',
  'inward': '向内',
  'outward': '向外',
  'vertical': '垂直',
  'horizontal': '水平',
  'diagonal': '对角',
  'isometric': '静力',
  'dynamic': '动态',
  'concentric': '向心',
  'eccentric': '离心',
  'negatives': '离心',
  'paused': '停顿',
  'tempo': '节奏',
  'alternating': '交替',
  'alternate': '交替',

  // 第二轮补充（常见动作名/残词）
  'lateral': '侧',
  'straight': '直',
  'pulldown': '高位下拉',
  'assisted': '助力',
  'overhead': '过顶',
  'behind': '后',
  'head': '头',
  'hammer': '锤式',
  'inverse': '反向',
  'dips': '臂屈伸',
  'russian': '俄罗斯',
  'suspended': '悬吊',
  'palm': '掌',
  'palms': '掌',
  'throw': '抛',
  'muscle': '肌肉',
  'planche': '水平支撑',
  'flexor': '屈肌',
  'sled': '雪橇',
  'wall': '墙',
  'donkey': '驴',
  'bike': '单车',
  'wheel': '轮',
  'chin': '反握',
  'tap': '点',
  'internal': '内',
  'external': '外',
  'pelvic': '骨盆',
  'tilt': '倾斜',
  'pike': '折叠',
  'frog': '蛙',
  'self': '自',
  'squatting': '深蹲',
  'kickback': '后踢',
  'raised': '抬高',
  'stance': '站姿',
  'french': '法式',
  'parallel': '平行',
  'half': '半',
  'jack': '开合',
  'archer': '弓',
  'scapula': '肩胛',
  'scapular': '肩胛',
  'twisted': '扭转',
  'roller': '滚',
  'rollerer': '滚',
  'windmill': '风车',
  'modified': '改良',
  'chair': '椅',
  'support': '支撑',
  'clasped': '交叉',
  'hug': '抱',
  'iron': '铁',
  'potty': '坐便',
  'hyper': '超',
  'hyperextension': '超伸展',
  'rocking': '摇摆',
  'flip': '翻',
  'world': '世界',
  'against': '靠',
  'posterior': '后侧',
  'skull': '颅',
  'crusher': '碎',
  'jm': 'JM',
  'pulley': '滑轮',
  'pushdown': '下压',
  'motion': '动',
  'stork': '鹳',
  'curls': '弯举',
  'handstand': '倒立',
  'bottoms': '底',
  'clean': '翻',
  'hang': '悬',
  'olympic': '奥运',
  'ski': '滑雪',
  'three': '三',
  'bars': '杠',
  'jumps': '跳',
  'trainer': '训练器',
  'stationary': '固定',
  'bradford': '布拉德福德',
  'rocky': '摇滚',
  'around': '绕',
  'fixed': '固定',
  'rotational': '旋转',
  'knees': '膝',
  'slam': '砸',
  'crossovers': '交叉',
  'point': '点',
  'response': '反应',
  'depresor': '下压',
  'retractor': '后缩',
  'slingers': '甩臂',
  'pallof': '帕洛夫',
  'sitted': '坐',
  'tuck': '收',
  'maltese': '马耳他',
  'straddle': '分腿',
  'gripper': '握力器',
  'apart': '分开',
  'rack': '架',
  'stiff': '直',
  'basic': '基础',
  'yoga': '瑜伽',
  'femoral': '股骨',
  'stepbox': '台阶',
  'legged': '腿',
  'farmers': '农夫',
  'flutter': '上下',
  'ham': '腘绳',
  'reversed': '反',
  'keens': '膝',
  'intermediate': '中级',
  'through': '过',
  'get': '起',
  'adduction': '内收',
  'monster': '怪兽',
  'outside': '外',
  'cobra': '眼镜蛇',
  'inside': '内',
  'reclining': '仰卧',
  'big': '大',
  'runners': '跑者',
  'angle': '角度',
  'sequence': '序列',
  'outstretched': '伸展',
  'platform': '台',
  'slide': '滑',
  'degrees': '度',
  'closer': '更近',
  'strap': '带',
  'abductor': '外展肌',
  'tire': '轮胎',
  'squats': '深蹲',
  'ankle': '踝',
  'circles': '画圈',
  'box': '箱',
  'stabilization': '稳定',
  'rotary': '旋转',
  'peroneals': '腓骨肌',
  'tibialis': '胫骨前肌',
  'angled': '斜',
  'pin': '销',
  'presses': '推举',
  'drive': '蹬',
  'diamond': '钻石',
  'bowling': '保龄',
  'bosu': 'BOSU球',
  'pronated': '旋前',
  'supinated': '旋后',
  'peacher': '牧师凳',
  'pronate': '旋前',
  'balance': '平衡',
  'tate': '泰特',
  'waiter': '侍者',
  'face': '面',
  'impossible': '不可能',
  'position': '姿势',
  'overhand': '正握',
  'ring': '吊环',
  'ergometer': '测功仪',
  'stalder': '斯塔尔德',
  'forth': '来回',
  'cycle': '单车',
  'bends': '弯',
  'scissor': '剪刀',
  'short': '短',
  'stride': '跨',
  'hops': '跳',
  'star': '星',
  'elliptical': '椭圆机',
  'walking': '行走',
  'treadmill': '跑步机',
  'skier': '滑雪者',
  'battling': '战',
  'ropes': '绳',
  'revers': '反',
  'delt': '三角肌',
  'can': '罐',
  'scott': '斯科特',
  'above': '上',
  'anti': '抗',
  'gravity': '重力',
  'jerk': '挺',
  'pirate': '海盗',
  'supper': '晚',
  'seesaw': '跷跷板',
  'left': '左',
  'hook': '钩',
  'boxing': '拳击',
  'round': '圆',
  'underhand': '反握',
  'elevated': '抬高',
  'thibaudeau': '蒂博多',
  'kayak': '皮划艇',
  'cambered': '弯杆',
  'elevator': '升降',
  'ground': '地面',
  'reps': '次',
  'gironda': '吉龙达',
  'sternum': '胸骨',
  'straps': '带',
  'unilateral': '单侧',
  'london': '伦敦',
  'catch': '接',
  'mixed': '混合',
  'towel': '毛巾',
  'skin': '皮',
  'cat': '猫',
  'sphinx': '狮身',
  'twin': '双',
  'upward': '向上',
  'facing': '面',
  'dog': '狗',
  'cage': '架',
  'pectoralis': '胸大肌',
  'major': '大',
  'guillotine': '断头台',
  'variation': '变式',
  'middle': '中',
  'clock': '钟',
  'flyes': '飞鸟',
  'depth': '深度',
  'wipers': '雨刷',
  'range': '范围',
  'korean': '韩式',
  'multiple': '多重',
  'release': '释放',
  'hindu': '印度',
  'plus': '加',
  'air': '空气',
  'touchers': '触',
  'rectus': '腹直肌',
  'femoris': '股',
  'knife': '刀',
  'ab': '腹',
  'butt': '臀',
  'judo': '柔道',
  'twists': '转体',
  'captains': '船长',
  'cocoons': '茧',
  'crab': '蟹',
  'dead': '死',
  'bug': '虫',
  'flag': '旗',
  'gorilla': '大猩猩',
  'groin': '腹股沟',
  'janda': '詹达',
  'advanced': '高阶',
  'figure': '形体',
  'lean': '倾斜',
  'negative': '离心',
  'otis': '奥蒂斯',
  'power': '力量',
  'prisoner': '囚徒',
  'quarter': '四分之一',
  'saw': '锯',
  'sledge': '大锤',
  'spell': '拼写',
  'caster': '脚轮',
  'fallout': '前倒',
  'wind': '风',
  'sprints': '冲刺',
  'sumo': '相扑',
  'goblet': '高脚杯',
  'swing': '摆',
  'trap bar': '六角杆',
  'trap': '斜方肌',
  'abduction': '外展',
  'pronation': '旋前',
  'supination': '旋后',
  'neutral': '对握',
  'extended': '伸展',
  'pass': '传',
  'backward': '后',
  'plyo': '增强',
  'sprint': '冲刺',
  'spider': '蜘蛛',
  'greatest': '最',
  'all fours': '四点支撑',
  'piriformis': '梨状肌',
  'quads': '股四头',
  'over head': '过顶',
  'split': '分腿',
  '45': '45',
  'degrees': '度',
  'arm': '臂',
  'arms': '臂',
  'body': '身',
  'one': '单',
  'two': '双',
  'step': '踏',
  'floor': '地面',
  'sit': '坐',
  'pose': '姿势',
  'up': '上',

  // 性别标注
  'male': '（男）',
  'female': '（女）',
};

// 需丢弃的停用词/版本号
const DROP = new Set([
  'the','a','an','on','to','with','and','or','for','of','in','is','are','you','your',
  'at','by','as','into','from','that','this','it','its','down','over','under','out',
  'off','via','per','v','ups','2','3','4','1','0','x','s','t','d','r','e','g',
]);

// 构建按长度降序的 DICT 条目
const ENTRIES = Object.entries(DICT).sort((a, b) => b[0].length - a[0].length);

function normalize(s) {
  return s.toLowerCase().replace(/\./g, ' ').replace(/-/g, ' ').replace(/\//g, ' ').replace(/\s+/g, ' ').trim();
}

function translateName(name) {
  let s = normalize(name);
  // 处理括号：male/female 保留，其余括号内容删除
  s = s.replace(/\(([^)]*)\)/g, (m, inner) => {
    const t = inner.trim();
    if (t === 'male' || t === 'female') return ' ' + t + ' ';
    return ' ';
  });
  s = normalize(s);

  const out = [];
  let i = 0;
  let leftover = '';
  while (i < s.length) {
    if (s[i] === ' ') { i++; continue; }
    let matched = false;
    for (const [key, zh] of ENTRIES) {
      if (s.startsWith(key, i)) {
        const after = i + key.length;
        const boundaryOk = after === s.length || s[after] === ' ';
        const beforeOk = i === 0 || s[i - 1] === ' ';
        if (boundaryOk && beforeOk) {
          out.push(zh);
          i = after;
          matched = true;
          break;
        }
      }
    }
    if (!matched) {
      let j = i;
      while (j < s.length && s[j] !== ' ') j++;
      const tok = s.slice(i, j);
      if (!DROP.has(tok)) leftover += (leftover ? ' ' : '') + tok;
      i = j;
    }
  }
  return { zh: out.join(''), leftover };
}

// ---- 执行 ----
const untranslated = data; // 全量重翻，统一风格
const leftoverTokens = new Map();
let changed = 0;
const samples = [];
const stillBad = [];
const withLeftover = [];

for (const x of untranslated) {
  const { zh, leftover } = translateName(x.name);
  if (leftover) {
    leftover.split(' ').forEach(t => leftoverTokens.set(t, (leftoverTokens.get(t) || 0) + 1));
    withLeftover.push(`${x.name}  =>  ${zh}  (剩:${leftover})`);
  }
  if (zh && zh !== x.name) {
    x.nameZh = zh;
    changed++;
    if (samples.length < 100 && (changed % 13 === 0)) samples.push(`${x.name}  =>  ${zh}`);
  } else {
    stillBad.push(`${x.name}  (剩: ${leftover || '空'})`);
  }
}

console.log('总条数:', untranslated.length, ' 写回:', changed, ' 仍失败:', stillBad.length);
console.log('--- 抽样(100) ---');
samples.forEach(s => console.log('  ' + s));
console.log('--- 仍有残留英文的词条 ---');
withLeftover.forEach(s => console.log('  ' + s));
console.log('--- 残留词 ---');
const lt = [...leftoverTokens.entries()].sort((a, b) => b[1] - a[1]);
console.log(lt.map(([w, c]) => w + ':' + c).join('  '));

// 写回
fs.writeFileSync(FILE, JSON.stringify(data, null, 2) + '\n', 'utf8');
console.log('已写回 exercises.json');
